ALTER TABLE `user_type`
CHANGE `id` `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE `users`
CHANGE `id` `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
CHANGE `account_type` `account_type` BIGINT UNSIGNED NULL DEFAULT NULL,
CHANGE `created_by_id` `created_by_id` BIGINT UNSIGNED NULL DEFAULT NULL;

ALTER TABLE users
ADD CONSTRAINT fk_account_type_users FOREIGN KEY (account_type) REFERENCES user_type (id) ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE `wallet_balance_history` ADD `trans_id` VARCHAR(50) NULL DEFAULT NULL AFTER `id`;